### PR TITLE
unlock all languages for everyone

### PR DESCRIPTION
**Pull request by paldier**
BR CN CZ DE EN ES FR HU IT JP KR MS NL PL RU RO SL TH TR TW UK
you can choose what you like on any asus's router

Signed-off-by: ZhaoWei Xu <paldier@hotmail.com>

### CODE REVIEW

**Comment by JackMerlin** [comment]
I support this pull, but I think Eric will not be merged into the code repository, because there is a reason why asus chose not to provide some languages on some national models. if we do not respect the decision made by asus, then asus may be closed in the future. so, that will make more difficult to maintain this project.

**Comment by RMerl** [comment]
I'll give it more thought, but my first reaction would indeed be to not merge this, as this could create a conflict with Asus.  If they moved that code into closed source components, it`s because they did not want me to override them.

**Comment by JackMerlin** [comment]
@paldier @RMerl 


> I'll give it more thought, but my first reaction would indeed be to not merge this, as this could create a conflict with Asus. If they moved that code into closed source components, it`s because they did not want me to override them.



If let me  to choose, I would rather sacrifice multi-languages support to choose openness. because that's why this project is so powerful.

BTW, I did lose other languages about a year ago. I cannot see French again. I can only use English. My model is from China. so this change may indeed help me, but I don't want to see asus close the source code, and I don't want to see this change merged into a future release.

**Comment by GravuTrad** [comment]
Strange to can't have a real multilanguage system with asus. Really tiring.

**Comment by RMerl** [comment]
Blame it on marketing.

In any case, I decided not to play a cat and mouse game with Asus, and won't be merging this change in.  Sorry.

**Comment by GravuTrad** [comment]
For sure it's normal. How to merge it in our perso nal router?

**Comment by JackMerlin** [comment]
> 
> 
> Blame it on marketing.
> 
> In any case, I decided not to play a cat and mouse game with Asus, and won't be merging this change in. Sorry.

Wise choice, I support you!

**Pull request closed without merging**
