### PR TITLE
Update DoT

### PR DESCRIPTION
**Pull request by maghuro**
Changed cloudflare, as they're using one.one.one.one as main one.
Add Applied Privacy on port 443 which is useful for European users, because servers are based in Austria (country with hard privacy laws)

### CODE REVIEW

**Comment by maghuro** [comment]
Forget about e9545c6, don't know why was it assumed as a pull request from me.

**Comment by dave14305** [comment]
Cloudflare is still serving a certificate with CN=cloudflare-dns.com on 1.1.1.1:853.

**Comment by maghuro** [comment]
You're absolutely right, my very bad. A better search and I read that.

**Comment by maghuro** [comment]
@dave14305
I was testing and I can only use cloudflare's DoT using 1dot1dot1dot1.cloudflare-dns.com or one.one.one.one
Just cloudflare-dns.com it won't connect...

**Comment by RMerl** [comment]
The official Cloudflare documentation still states cloudflare-dns.com should be used.

https://developers.cloudflare.com/1.1.1.1/dns-over-tls/

**Comment by maghuro** [comment]
Correct
And regarding Applied Privacy?

**Comment by RMerl** [comment]
No plan to add it.  I want to keep the list short, with either well-known services, or services that provide something unique (hence the presence of one service that uses a non-standard port).  Too many services will only confuse the users, and will increase my workload as I will have to constantly add or remove services.

**Pull request closed without merging**
