### PR TITLE
Question About Supported Devices

### PR DESCRIPTION
**Pull request by KingOwnageXV**
Why does Merlin not support "RT-AC1200" and  "RT-AC1200 V2"? Is it not possible? People on reddit said it should be when asked, so if it is then I'd like to know why it isn't.

### CODE REVIEW

**Comment by KingOwnageXV** [comment]
Instead of closing it, you could respond first.

**Comment by RMerl** [comment]
What you just did was not ask a question, it was creating a pull request that would have merged code into this repository, hence it was closed.

If you need support, use the support forums, don't create bogus code pull requests.

**Comment by KingOwnageXV** [comment]
Mate I don't know how to use github, it is extremely unuser friendly to new users, there is a learning curve but I do remember in the past I saw a place to post questions on a different page but for some reason I could not find it again on this specific page. I guess I'm either just having worse luck finding it or you disabled it here for some reason. 

Either way you could of replied answering my question and also informing me what a pull request was, not ignoring my question entirely and saying something passive aggressive like "don't create bogus code pull request" when its obvious it was an accident.

**Comment by asaddon** [comment]
@KingOwnageXV It seems you are not a developer and you're still using a developer portal for your non-development related questions. How can you expect us (developers) to stop our work and teach you about a simple concept of "pull request" (Google is your friend here) we're not here for that nor this issue tracker. 

Just use the official Asuswrt-Merlin support forum for any such questions. 

https://www.snbforums.com/forums/asuswrt-merlin.42/

**Comment by KingOwnageXV** [comment]
Its simple because you've been using github for a long time, this is my 2nd time on it and you spent more time bitching than informing me what a pull request was, so you just debunked your own point about not having enough time. Have a good day though, just learn how to manage your time better since you're such a busy person, and remember first impressions matter so approach situations with a good attitude. Goodbye mate

**Pull request closed without merging**
