### PR TITLE
httpd: Fix wireless password strength check with WPA3

### PR DESCRIPTION
**Pull request by Adamm00**

### CODE REVIEW

**Comment by asaddon** [comment]
@RMerl already fixed it in https://github.com/RMerl/asuswrt-merlin.ng/commit/92c32ae843d0d2091a2ba28ca0a106d472a52431

**Comment by Adamm00** [comment]
Different bug (but similar), this is for the password strength indicator, not the wireless encryption

**Comment by asaddon** [comment]
Ah Okay!!

**Comment by Adamm00** [comment]
Did a test compile just to make sure it works;

Before;
https://i.imgur.com/Dmu6hQU.png

After;
https://i.imgur.com/H36N4m4.png

**Pull request merged**
